services:
  db:
    container_name: gamelib-postgres
    image: postgres:17.0
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432" # Puerto por defecto es 5432 si no se establece la variable DB_PORT en el .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data # Se guarda en la carpeta postgress en la raiz del proyecto junto al compose.yml